export const topics = [
    'adventure',
    'advice',
    'advertising',
    'anime',
    'ama',
    'african',
    'agriculture',
    'apps',
    'art',
    'artificial intelligence',
    'asian',
    'ask',
    'babies',
    'baptism',
    'basketball',
    'Bible',
    'biology',
    'books',
    'brain',
    'budget',
    'business',
    'cancer treatment',
    'cars',
    'cartoons',
    'celeb',
    'children',
    'Christianity',
    'cities',
    'coding',
    'collectors',
    'college',
    'college basketball',
    'college football',
    'combat',
    'community',
    'company',
    'computers',
    'computer science',
    'cooking',
    'crafts',
    'curiosity',
    'dating',
    'dental',
    'design',
    'diet',
    'discovery',
    'disease',
    'dogs',
    'drug rehab',
    'earth',
    'elections',
    'education',
    'energy',
    'engineering',
    'environment',
    'entertainment',
    'europe',
    'evangelism',
    'experiment',
    'expert',
    'exploring',
    'farming',
    'family',
    'film',
    'finance',
    'fitness',
    'food',
    'future',
    'gardening',
    'God',
    'guns',
    'hair',
    'hardware',
    'health',
    'healthcare',
    'history',
    'historical events',
    'historical places',
    'home',
    'instruments',
    'internet',
    'inventions',
    'investing',
    'Jesus',
    'Judaism',
    'language',
    'law',
    'lifestyle',
    'logic',
    'love',
    'machine learning',
    'marketing',
    'martial arts',
    'math',
    'media',
    'medical',
    'medicine',
    'men',
    'mental health',
    'mlb',
    'major league soccer',
    'mma',
    'music',
    'natural language processing',
    'natural resources',
    'nature',
    'news',
    'nfl',
    'nhl',
    'night life',
    'parenting',
    'photography',
    'pickup',
    'planes',
    'podcast',
    'poetry',
    'politics',
    'products',
    'programming',
    'psychology',
    'reading',
    'real estate',
    'relationships',
    'running',
    'science',
    'shows',
    'sewing',
    'school',
    'skateboarding',
    'space',
    'sports',
    'startups',
    'statistics',
    'stock market',
    'streaming',
    'telecommunications',
    'tools',
    'towns',
    'travel',
    'technology',
    'video games',
    'waffles',
    'war',
    'weather',
    'weights',
    'weight loss',
    'women',
    "women's health",
    'world news',
    'working out',
    'writing',
];